using System;
using System.Collections.Generic;

public class DialogScripts
{
    private DialogScripts ()
    {
    }

    public static int GetIndex (string[] script, string sentence)
    {
        return Array.IndexOf<string> (script, sentence);
    }


    public static string[] Male1Script = new string[] {
        "Estava curioso em saber se vinha, aproveito para informar que sairam as notas dos testes de AL e FP.",
        "Quero lembrá-lo que tem um checkpoint em duas semanas.",
        "Não podemos fazer nada disso agora. Malditos programadores.",
        "Aqui poderá consultar informação referente às cadeiras.",
        "Deveria ter estudado mais...",
        "Pode ser que suba a nota.",
        "Talvez deveria ter estudado mais",
        "Ainda penso que um plano de estudo seria bom.",
        "Ainda há espaço para melhorar.",
        "Continue o bom trabalho.", 
        "Apenas essas horas é capaz de correr mal.",
        "Eu sei que te digo para estudar mais mas isto é demais.",
        "Aconselho-te a diminuir um pouco as horas.",
        "Espero que o consiga manter.",
        "Espero que venha.",
        "Talvez não nos queira ver.",
        "Vou desligar a aplicação então.",
        "Ele não sabe, nem toda a gente sabe isso.",
        "Talvez não queira falar connosco.",
        "É melhor desligarmos então.",
        "Aconselho a fazer um plano de estudo para gerir o seu tempo.",
        "Ok they wants to insist in this bad plan",
        "Espero que tenha corrido bem.",
        "Anything you need, do not lean on my partner",
        "Por agora só sabemos isso.",
        "Por favor não de problemas pessoais.",
        "Em AL teve um 14 no primeiro teste e um 12 no segundo e acabou de receber mais um.",
        "As coisas estão a correr bem a FP mas em AL estão a piorar.",
        "Estude com antecedência.",
        "Não há vergonha em tentar gerir o seu tempo.",
        "Esta cadeira é demasiado importante para isso.",
        "O que pretende fazer?",
        "Notificá-lo-emos da sua situação.",
        "É isso que pretende?",
        "Para Álgebra recomendamos estudar 5 horas semanais e para Fundamentos da Programação 4 horas semanais.",
        "Estou muito triste.",
        "Falaremos com o seu tutor para avisar da situação."
    };

    public static string[] Female1Script = new string[] {
        "Olá, é bom vê-lo depois destes dois dias.",
        "Em que o podemos ajudar?",
        "Assim que tivermos esta funcionalidade falaremos contigo.",
        "Oh não!",
        "Talvez fazer um plano de estudo o ajude.",
        "Este teste não foi o esperado.",
        "Aconselho a fazer um plano de estudo para tentar melhorar a nota.",
        "Tudo bem, com isto será notificado antes.",
        "Parabéns por uma boa nota.",
        "Ainda assim é muito bom.",
        "Parabéns por uma nota brilhante!",
        "Não sei se só isto é boa ideia, tens a certeza?",
        "Isto não te parece demasiado?",
        "Se não tiveres tempo para descansar não vais usar o teu potencial máximo.",
        "Podemos ajudar em algo mais?",
        "Venha ver-nos em 2 dias para vermos se o plano funciona.",
        "Quando quer ter uma nova reunião?",
        "Ok, vejo-o em 2 dias!",
        "Tudo bem, vemo-nos em 5 dias!",
        "Tudo bem, vemo-nos em 7 dias.",
        "Vemo-nos quando aparecer.",
        "E agora?",
        "Suponho que não queira falar sobre isso.",
        "We have to trust them", 
        "Será  que vai ver os resultados de uma avaliação?",
        "Sabemos que tem um momento importante daqui a 10 dias.",
        "Do que gostaria de falar?",
        "Em FP sabemos que teve um 12 no teste e um 16 no projeto, além do teste que acabou de receber.",
        "Continue o bom trabalho a FP mas tente melhorar AL.", 
        "Faça um plano de estudo e cumpra-o.",
        "Se desistir da cadeira, vamos deixar de dar apoio nesta em prol das outras.",
        "É isso que quer?",
        "Tente não desistir por agora.", 
        "Se quiser podemos contatar o tutor.",
        "Se precisar mesmo, podemos contatar o seu tutor.",
        "Abriremos o seu google calendar para que possa planear as horas de estudo desta semana.",
        "Oh não!",
        "Quer que façamos um plano de estudo?"
    };

    public static string[] Female2Script = new string[] {
        "Bom dia amigo, é bom vê-lo depois destes dois dias, aporveito para o informar que as notas de AL e FP já saíram.",
        "Em que o podemos ajudar?",
        "Assim que tivermos esta funcionalidade falaremos contigo.",
        "Epá, que azar! O que aconteceu aqui?",
        "Um plano de estudo vai ajudá-lo.",
        "Isto não é costume para si.",
        "Uma alternativa é fazer um plano de estudo para tentar melhorar a nota.",
        "Ok, será notificado ainda mais cedo.",
        "Parabéns, que nota boa.",
        "Ainda assim é muito bom.",
        "Parabéns por uma nota fantástica!",
        "Não sei se só isto é boa ideia, tens a certeza?",
        "Isto não te parece demasiado?",
        "Se não tiveres tempo para descansar não vais usar o teu potencial máximo.",
        "Ok ótimo, já temos plano de estudo.", 
        "Podemos ajudar em algo mais?",
        "Venha ver-nos em 2 dias para falarmos de outras coisas.",
        "Quando quer ter uma nova reunião?",
        "Ok, vejo-o em 2 dias!",
        "Tudo bem, vemo-nos em 5 dias!", 
        "Tudo bem, vemo-nos em 7 dias",
        "Vemo-nos quando aparecer",
        "E agora?",
        "É normal se não quiser falar sobre isso.",
        "Nós apoiamos!",
        "Será  que vai ver os resultados de uma avaliação?",
        "Estamos à espera que o professor coloque a época de recurso no Moodle.",
        "Do que gostaria de falar hoje?",
        "Em FP sabemos que teve um 12 no teste, um 16 no projeto e um 20 no segundo teste, além do teste que acabou de receber.",
        "Continue o bom trabalho a FP mas tente melhorar AL talvez fazer uma melhoria de nota.",
        "Faça um plano de estudo e cumpra-o.",
        "Se desistir da cadeira, vamos deixar de dar apoio nesta em prol das outras.",
        "É isso que quer?",
        "Não desista, companheiro.",
        "Quer que contactemos o seu tutor?",
        "Se precisar, contataremos o seu tutor.",
        "Abriremos o seu google calendar para que possa planear as horas de estudo desta semana.",
        "Oh não, foi mesmo abaixo do que estávamos à espera!",
        "Quer que façamos um plano de estudo? Vamos melhorar isto."
    };

    public static string[] Male2Script = new string[] {
        "Estava curioso em saber se vinha, pode consultar as notas das cadeiras nos seus respetivos menus.",
        "Não podemos fazer nada disso agora. Malditos programadores.",
        "Como sabe, aqui é onde vem para ver a informação das suas cadeiras.",
        "Acho que devia ter estudado mais...",
        "Com ele vai poder estudar para o exame final e épica de recurso.",
        "Devia ter estudado mais.",
        "Não ignore o plano de estudo, acho que é a melhor coisa para si.",
        "Ainda há espaço para melhorar, sei que consegue fazer melhor.",
        "Continue o bom trabalho",
        "Sim, sabia que conseguia.",
        "Apenas essas horas é capaz de correr mal.",
        "Eu sei que te digo para estudar mais mas isto é demais.",
        "Aconselho-te a diminuir um pouco as horas.",
        "Sei que vai conseguir mantê-lo.",
        "Tenho confiança que vai tudo correr bem até lá.",
        "Zangou-se connosco e já não nos quer.",
        "Vou desligar a aplicação então.",
        "Ele não sabe, nem toda a gente sabe isso.",
        "Talvez não queira falar connosco.",
        "É melhor desligarmos então.",
        "Vamos fazer um plano de estudo para gerir os problemas da semana que vem.",
        "Se achas que é o melhor para si, eu apoio.",
        "Espero que tenha corrido bem.",
        "Anything you need, do not lean on my partner",
        "Por agora só sabemos isso.",
        "Por favor nada de problemas pessoais.",
        "Em AL teve um 14 no primeiro teste, um 12 no segundo,um 13 no terceiro e acabou de receber mais um.",
        "As coisas estão a correr bem a FP mas em AL estão a piorar.",
        "Estude com antecedência para a época de recurso de AL.",
        "Já sabe que não há vergonha em tentar gerir o seu tempo.",
        "Esta cadeira é demasiado importante para isso.",
        "O que pretende fazer?",
        "Notificá-lo-emos da sua situação.",
        "É isso que pretende?",
        "Para Álgebra recomendamos estudar 5 horas semanais e para Fundamentos da Programação 4 horas semanais.",
        "Estou muito triste.",
        "Falaremos com o seu tutor para avisar da situação."
    };
}

